version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - ./app:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admintest
      POSTGRES_DB: trans_db
    ports:
      - "5433:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
