# Generated by Django 5.1.6 on 2025-02-19 07:09

import django.core.validators
import myapp.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player1', models.CharField(blank=True, max_length=255, null=True)),
                ('player2', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('difficulty', models.CharField(default='medium', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='open', max_length=7)),
                ('players', models.JSONField(default=list)),
                ('games', models.JSONField(default=list)),
                ('first', models.CharField(blank=True, max_length=20, null=True)),
                ('second', models.CharField(blank=True, max_length=20, null=True)),
                ('third', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('image_avatar', models.ImageField(blank=True, default=myapp.models.get_default_avatar, null=True, upload_to='avatar/')),
                ('nb_game_play', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nb_game_win', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default='#ff79d1', max_length=7)),
                ('is_online', models.BooleanField(default=False)),
                ('games_history', models.JSONField(default=dict)),
                ('nb_friends', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
