# Generated by Django 5.1.5 on 2025-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_tournament_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='first',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
