# Generated by Django 5.1.5 on 2025-02-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_player_nb_game_play_alter_player_nb_game_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='games_history',
            field=models.JSONField(default=dict),
        ),
    ]
