# Generated by Django 5.1.5 on 2025-02-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tournament_first_tournament_second_tournament_third'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='first',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='second',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='third',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
