services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
      - "4438:4438"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - django


  django:
    build:
      context: ./django
    container_name: django-container
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "myproject.asgi:application"]
    volumes:
      - ./django/app:/app
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./django/.env
    depends_on:
      - db
  

  db:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: maxime
      POSTGRES_PASSWORD: maxou
      POSTGRES_DB: new_Post
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: