
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/usr/share/nginx/html:ro
      - ./app/staticfiles:/app/staticfiles
    depends_on:
      - django

  django:
    build:
      context: ./django
    container_name: django-container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django/app:/app
      - ./static:/app/static
      - ./app/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./django/.env
